In [1]:
import pandas as pd

In [2]:
members = pd.read_csv(r"D:\code\SQL\Practice\8weeksqlchallenge\01_dannys_diner\raw_data\members.csv")
menu = pd.read_csv(r"D:\code\SQL\Practice\8weeksqlchallenge\01_dannys_diner\raw_data\menu.csv")
sales = pd.read_csv(r"D:\code\SQL\Practice\8weeksqlchallenge\01_dannys_diner\raw_data\sales.csv")

In [3]:
members.head()

  customer_id   join_date
0           A  07-01-2021
1           B  09-01-2021

In [4]:
menu.head()

   product_id product_name  price
0           1        sushi     10
1           2        curry     15
2           3        ramen     12

In [5]:
sales

   customer_id  order_date  product_id
0            A  01-01-2021           1
1            A  01-01-2021           2
2            A  07-01-2021           2
3            A  10-01-2021           3
4            A  11-01-2021           3
5            A  11-01-2021           3
6            B  01-01-2021           2
7            B  02-01-2021           2
8            B  04-01-2021           1
9            B  11-01-2021           1
10           B  16-01-2021           3
11           B  01-02-2021           3
12           C  01-01-2021           3
13           C  01-01-2021           3
14           C  07-01-2021           3

## Question 1
### What is the total amount each customer spent at the restaurant?

In [6]:
# df = sales & menu merged
df = sales.merge(menu, on='product_id', how='left')

In [7]:
sol_1 = df.groupby('customer_id').agg(total_spent=('price', 'sum')).reset_index()

In [8]:
sol_1

  customer_id  total_spent
0           A           76
1           B           74
2           C           36

## Question 2

### How many days has each customer visited the restaurant?
##### Restatement: No. of days a customer visited the restaurant
##### Output Grain: One record per customer

In [9]:
result_2 = sales.groupby('customer_id').agg(visit_count = ('order_date', 'nunique')).reset_index()
print(result_2)

  customer_id  visit_count
0           A            4
1           B            6
2           C            2

## Question 3

### What was the first item from the menu purchased by each customer?

#### Restatement: Customer's first purchase
#### Output Grain: One Record Per Customer of Item Purchased
#### First order ambiguous because multiple record for a customer could be on the same day

In [10]:
result_3 = (
    df.sort_values(['customer_id','order_date'], ascending=True)
    .groupby('customer_id')['product_name']
    .first()
    .reset_index()
    )
print(result_3)

  customer_id product_name
0           A        sushi
1           B        curry
2           C        ramen

## Question 4

### What is the most purchased item on the menu and how many times was it purchased by all customers?

#### Restatement: Overall what item was purchased the most and how many times
#### Granularity: Product | Purchase_Count

In [11]:
result_4 = (
    df.groupby('product_name')
    .agg(Product_Count=('order_date','count'))
    .sort_values(by='Product_Count', ascending=False)
    .head(1)
    .reset_index()
    )

print(result_4)

  product_name  Product_Count
0        ramen              8

## Question 5

### Which item was the most popular for each customer?
#### Restatement: Per Customer what was the most purchased product
#### Granularity: Customer | Most Purchased product

In [19]:
result = result_5[
    result_5['Order_Count']
    == result_5.groupby('customer_id')['Order_Count'].transform('max')
]
result

  customer_id product_name  Order_Count
1           A        ramen            3
3           B        curry            2
4           B        ramen            2
5           B        sushi            2
6           C        ramen            3

In [27]:
i = (
    df.groupby(['customer_id', 'product_name'])
    .agg(Order_Count = ('order_date', 'count'))
    .reset_index()
    )

In [29]:
result5 = i[
    i['Order_Count']
    == i.groupby('customer_id')['Order_Count'].transform('max')
][['customer_id', 'product_name']]
result5

  customer_id product_name
1           A        ramen
3           B        curry
4           B        ramen
5           B        sushi
6           C        ramen

## Question 6

### Which item was purchased first by the customer after they became a member?

## Question 7

### Which item was purchased just before the customer became a member?

## Question 8

### What is the total items and amount spent for each member before they became a member?

## Question 9

### If each $1 spent equates to 10 points and sushi has a 2x points multiplier, how many points would each customer have?

## Question 10

### In the first week after a customer joins the program they earn 2x points on all items. How many points do customer A and B have at the end of January?