In [1]:
import pandas as pd

In [5]:
members = pd.read_csv(r"D:\code\SQL\Practice\8weeksqlchallenge\01_dannys_diner\raw_data\members.csv")
menu = pd.read_csv(r"D:\code\SQL\Practice\8weeksqlchallenge\01_dannys_diner\raw_data\menu.csv")
sales = pd.read_csv(r"D:\code\SQL\Practice\8weeksqlchallenge\01_dannys_diner\raw_data\sales.csv")

In [ ]:
members.head()

  customer_id   join_date
0           A  07-01-2021
1           B  09-01-2021

In [7]:
menu.head()

   product_id product_name  price
0           1        sushi     10
1           2        curry     15
2           3        ramen     12

In [8]:
sales.head()

  customer_id  order_date  product_id
0           A  01-01-2021           1
1           A  01-01-2021           2
2           A  07-01-2021           2
3           A  10-01-2021           3
4           A  11-01-2021           3

## Question 1
### What is the total amount each customer spent at the restaurant?

## Question 2

### How many days has each customer visited the restaurant?

## Question 3

### What was the first item from the menu purchased by each customer?

## Question 4

### What is the most purchased item on the menu and how many times was it purchased by all customers?

## Question 5

### Which item was the most popular for each customer?

## Question 6

### Which item was purchased first by the customer after they became a member?

## Question 7

### Which item was purchased just before the customer became a member?

## Question 8

### What is the total items and amount spent for each member before they became a member?

## Question 9

### If each $1 spent equates to 10 points and sushi has a 2x points multiplier, how many points would each customer have?

## Question 10

### In the first week after a customer joins the program they earn 2x points on all items. How many points do customer A and B have at the end of January?