In [1]:
import pandas as pd

In [2]:
# Loading Raw Data
customer_orders = pd.read_csv(r'D:/code/SQL/Practice/8weeksqlchallenge/02_pizza_runner/raw_data/customer_orders.csv')
pizza_names = pd.read_csv(r'D:/code/SQL/Practice/8weeksqlchallenge/02_pizza_runner/raw_data/pizza_names.csv')
pizza_recipes = pd.read_csv(r'D:/code/SQL/Practice/8weeksqlchallenge/02_pizza_runner/raw_data/pizza_recipes.csv')
pizza_toppings = pd.read_csv(r'D:/code/SQL/Practice/8weeksqlchallenge/02_pizza_runner/raw_data/pizza_toppings.csv')
runner_orders = pd.read_csv(r'D:/code/SQL/Practice/8weeksqlchallenge/02_pizza_runner/raw_data/runner_orders.csv')
runners = pd.read_csv(r'D:/code/SQL/Practice/8weeksqlchallenge/02_pizza_runner/raw_data/runners.csv')

In [3]:
customer_orders.head()

   order_id  customer_id  pizza_id exclusions extras           order_time
0         1          101         1        NaN    NaN  2021-01-01 18:05:02
1         2          101         1        NaN    NaN  2021-01-01 19:00:52
2         3          102         1        NaN    NaN  2021-01-02 23:51:23
3         3          102         2        NaN    NaN  2021-01-02 23:51:23
4         4          103         1          4    NaN  2021-01-04 13:23:46

In [4]:
runner_orders.head()

   order_id  runner_id          pickup_time distance    duration cancellation
0         1          1  2021-01-01 18:15:34     20km  32 minutes          NaN
1         2          1  2021-01-01 19:10:54     20km  27 minutes          NaN
2         3          1  2021-01-03 00:12:37   13.4km     20 mins          NaN
3         4          2  2021-01-04 13:53:03   23.4km          40          NaN
4         5          3  2021-01-08 21:10:57     10km          15          NaN

# 8 Week SQL Challenge — Week 2: Pizza Runner

## Question 1

How many pizzas were ordered?

In [5]:
pizzas_ordered = customer_orders['pizza_id'].count()
print(f"Ordered Pizza Count: {pizzas_ordered}")

Ordered Pizza Count: 14

## Question 2

How many unique customer orders were made?

In [6]:
orders_made = customer_orders['order_id'].nunique()
print(f"Orders Count: {orders_made}")

Orders Count: 10

## Question 3

How many successful orders were delivered by each runner?

## Question 4

How many of each type of pizza was delivered?

## Question 5

How many Vegetarian and Meatlovers pizzas were ordered by each customer?

## Question 6

What was the maximum number of pizzas delivered in a single order?

## Question 7

For each customer, how many delivered pizzas had at least 1 change and how many had no changes?

## Question 8

How many pizzas were delivered that had both exclusions and extras?

## Question 9

What was the total volume of pizzas ordered for each hour of the day?

## Question 10

What was the volume of orders for each day of the week?

## Question 11

How many runners signed up for each 1 week period?

## Question 12

What was the average time in minutes it took for each runner to arrive at the Pizza Runner HQ to pick up the order?

## Question 13

Is there any relationship between the number of pizzas and how long the order takes to prepare?

## Question 14

What was the average distance travelled for each customer?

## Question 15

What was the difference between the longest and shortest delivery times for all orders?

## Question 16

What was the average speed for each runner for each delivery?

## Question 17

What is the successful delivery percentage for each runner?